
# -------------------------------
# CUSTOM BINDINGS
# -------------------------------
# Easy reload
unbind r
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded config file."

# Set Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Remove status right
set-option -g status-right ""

# Vim-like navigation
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set true colour
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ',alacritty:RGB'
set -g mouse on

# Status bar
set -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'xamut/tmux-spotify'

set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @tmux-nerd-font-window-name-show-name true

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

# https://github.com/jaclu/tmux-menus
set -g @plugin 'jaclu/tmux-menus'

# -------------------------------
# DRACULE CONFIG
# -------------------------------
# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-empty-plugins false
# set -g @dracula-show-left-icon '🚀'
# set -g @dracula-left-icon-padding 0
# set -g @dracula-show-fahrenheit false
# set -g @dracula-plugins "spotify-tui weather time git battery"
# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-weather-colors "dark_gray white"
# set -g @dracula-time-colors "dark_purple white"
# set -g @dracula-git-colors "dark_gray yellow"
# set -g @dracula-battery-colors "dark_gray white"
# set -g @dracula-battery-label "🔋"
# set -g @dracula-show-timezone false
# set -g @dracula-day-month false
# set -g @dracula-military-time true
# set -g @dracula-show-location false
# set -g @dracula-clients-minimum 1

# ---------------------------------------------------------------
# Initialize TMUX plugin manager 
# keep this line at the very bottom of tmux.conf
# ---------------------------------------------------------------
run '~/.tmux/plugins/tpm/tpm'

