# ---------------- GLOBAL ---------------- #
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = """
$username $hostname $directory\
$fill\
${custom.readme} $cmd_duration $memory_usage $jobs $time $battery\
$line_break\
$nodejs\
$package\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$terraform\
$fill\
$status\
$line_break\
$character"""

# ---------------- PROMPT ---------------- #
command_timeout = 5000
scan_timeout=500

# ------------ BATTERY MODULE ------------ #
[battery]
full_symbol = "🔋 "
format="[$symbol$percentage]($style)"

[[battery.display]]
threshold = 100
style = "bold #ACFFAD"
charging_symbol = "🔌 "
discharging_symbol = "🔋 "

[[battery.display]]
threshold = 50
style = "bold #FFE194"
charging_symbol = "🔌 "
discharging_symbol = "😒 "

[[battery.display]]
threshold = 35
style = "bold #FF7600"
charging_symbol = "🔌 "
discharging_symbol = "😱 "

[[battery.display]]
threshold = 20
style = "bold #FF616D"
charging_symbol = "🔌 "
discharging_symbol = "☠️ "

# ------------ CHARACTER MODULE ------------ #
[character]
success_symbol = "[⇢](bold #ACFFAD) "
error_symbol = "[✗](bold #FF616D) "

# ------------ DIRECTORY MODULE ------------ #
[directory]
truncation_length = 8
truncation_symbol = "…/"

# ------------ GIT BRANCH MODULE ------------ #
[git_branch]
symbol = "🌱 "
truncation_length = 30
truncation_symbol = "..."
format = "[$symbol$branch]($style)"

# ------------ GIT COMMIT MODULE ------------ #
[git_commit]
commit_hash_length = 7
tag_symbol = " 🏷 "

# ------------ GIT STATE MODULE ------------ #
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold #FF616D)"

# ------------ GIT METRICS MODULE ------------ #
[git_metrics]
added_style = "bold #1CC5DC"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# ------------ GIT STATUS MODULE ------------ #
[git_status]
conflicted = " 🛑 "
diverged = " 😵 ⇡ ${ahead_count} 😱 ⇣ ${behind_count} "
staged = ' [++\($count\)](#ACFFAD) '

# ------------ HOSTNAME MODULE ------------ #
[hostname]
ssh_only = false
format =  "@ [$hostname](bold #FFE194) "
trim_at = ".companyname.com"
disabled = false

# ------------ PACKAGE MODULE ------------ #
[package]
format = "via [🎁 $version](208 bold) "

# ------------ TIME MODULE ------------ #
[time]
disabled = false
format = '[$time]($style)'
style = "bold #F1F1F1"

# ------------ USERNAME MODULE ------------ #
[username]
style_user = "#1CC5DC bold"
style_root = "#FF616D bold"
format = "[$user]($style)"
disabled = false
show_always = true

# ------------ CMD MODULE ------------ #
[cmd_duration]
format = "[$duration]($style)"
style = "#e467f2"

# ------------ FILL MODULE ------------ #
[fill]
symbol = " "

# ------------ JOBS MODULE ------------ #
[jobs]
symbol = "👷 "
format = "[$symbol$count]($style)"
style = "bold #FF616D"
number_threshold = 1

# ------------ MEMORY MODULE ------------ #
[memory_usage]
disabled = false
threshold = 75
format = "[$symbol$ram( | $swap)]($style)"
symbol = "🧠 "

# ------------ NODE MODULE ------------ #
[nodejs]
format = "via [🤖 $version](bold green) "

# ------------ STATUS MODULE ------------ #
[status]
style = "bg:blue"
symbol = "🔴 "
success_symbol = "🟢 SUCCESS"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

# ------------ TERRAFORM MODULE ------------ #
[terraform]
format = "[🏎💨 $version$workspace]($style) "
